export const creditCardAccountFieldSchema = {
  id: "string",
  name: "string",
  issuer: "string",
  currentBalance: "number",
  creditLimit: "number",
  standardApr: "number",
  minimumPayment: "number",
  dueDayOfMonth: "number",
  statementDayOfMonth: "number | null",
  lastPaymentDate: "ISO date | null",
  lastKnownStatementDate: "ISO date | null",
  hasPromoApr: "boolean",
  promoApr: "number | null",
  promoEndDate: "ISO date | null",
  aprAfterPromo: "number | null",
  isDeferredInterest: "boolean",
  deferredInterestAprBasis: "number | null",
  deferredInterestStartDate: "ISO date | null",
  hasSplitBalances: "boolean",
  balanceBuckets: "BalanceBucket[] | null",
  annualFee: "number | null",
  notes: "string | null",
  isClosed: "boolean",
  createdAt: "ISO datetime",
  updatedAt: "ISO datetime",
} as const;
